version : '3.7'

services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: nexusdb
    environment:
      - MYSQL_DATABASE=nexusdb
      - MYSQL_ROOT_PASSWORD=123321
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
